PODMAN?=		podman
PODMAN_OPTS?=

## ======================================================================

_C_MANAGER_OPTS=	$(PODMAN_OPTS)

## ----------------------------------------------------------------------

C_BUILDER?=		$(C_MANAGER) $(PODMAN_OPTS)

_C_BUILDER_ENV=	

_C_BUILDER_BUILD_OPTS=	--tag $(IMAGE_NAME)

## ----------------------------------------------------------------------

C_UNSHARE?=		$(C_MANAGER) unshare
