# syntax=docker.io/docker/dockerfile:1
# -*- coding: utf-8 -*- vim:shiftwidth=2:expandtab:

ARG from="docker.io/debian:bookworm-slim"

## ======================================================================

FROM ${from} AS apt-cache

LABEL maintainer="SATOH Fumiyasu"

ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND="noninteractive"

COPY PDFStudioViewer_linux64.sh .

RUN <<EOF
  set -ex
  apt-get update
  apt-get install --yes --quiet --no-install-recommends \
    ca-certificates \
    curl \
    libx11-6 \
    libxext6 \
    libxtst6 \
    libxrender1 \
    libfreetype6 \
    fontconfig \
    fonts-droid-fallback \
  ;
  if [ ! -s PDFStudioViewer_linux64.sh ]; then
    curl \
      --silent \
      --show-error \
      --remote-name \
      https://download.qoppa.com/pdfstudioviewer/PDFStudioViewer_linux64.sh \
    ;
  fi
  sh /PDFStudioViewer_linux64.sh \
    -q \
    -c \
    -dir /usr/local/pdfstudioviewer \
  ;
  ln -s \
    /usr/local/pdfstudioviewer/pdfstudioviewer20?? \
    /usr/local/bin/pdfstudioviewer \
  ;
EOF
